# Generated by Django 5.1.2 on 2024-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
