# Generated by Django 5.1.1 on 2024-10-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="preview",
            field=models.ImageField(
                blank=True,
                default="photos/default.jpg",
                null=True,
                upload_to="photos/",
                verbose_name="Изображение",
            ),
        ),
    ]
