# Generated by Django 5.1.1 on 2024-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="URL"),
        ),
    ]
