# Generated by Django 5.1.1 on 2024-10-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
