# Generated by Django 5.1.1 on 2024-10-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="interval",
            field=models.IntegerField(default=30),
        ),
    ]
