# Generated by Django 5.1.1 on 2024-10-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="photos/default.jpg",
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="photos/",
                verbose_name="Изображение (превью)",
            ),
        ),
    ]
